module.exports = new Map([
    ["Jane", {service: "hubspot", access_token: "CLqN6ZrjMBIIAAEAUAAAACAYmOi2CyDAjNQXKJLmVjIUO7Eev3ZCP9-DLEjW0_kWoLxEyj46MAAAAEEAAAAAAAAAAAAAAAAAhgAAAAAAAAAAAAAAAAAAAGAwAAAAAABAAAAAAAAAAkIUWEqUrD7ao8206hXap5NJ27IwmglKA25hMVIAWgA"}],
    ["Tom", {service: "hubspot", access_token: "CLqN6ZrjMBIIAAEAUAAAACAYmOi2CyDAjNQXKJLmVjIUO7Eev3ZCP9-DLEjW0_kWoLxEyj46MAAAAEEAAAAAAAAAAAAAAAAAhgAAAAAAAAAAAAAAAAAAAGAwAAAAAABAAAAAAAAAAkIUWEqUrD7ao8206hXap5NJ27IwmglKA25hMVIAWgA"}],
    ["Joe", {service: "hubspot", access_token: "CLqN6ZrjMBIIAAEAUAAAACAYmOi2CyDAjNQXKJLmVjIUO7Eev3ZCP9-DLEjW0_kWoLxEyj46MAAAAEEAAAAAAAAAAAAAAAAAhgAAAAAAAAAAAAAAAAAAAGAwAAAAAABAAAAAAAAAAkIUWEqUrD7ao8206hXap5NJ27IwmglKA25hMVIAWgA"}],
]);